#!/usr/bin/env bash
set -eo pipefail; [[ $JZ_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"

#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

plugin_main_cmd() {

    dist_zip="apache-tomee-7.1.0-plume.zip"

    if [ ! -f $JZ_CACHE/$dist_zip ]; then
        log_info "Downloading $dist_zip to $JZ_CACHE ..."
        curl http://ftp-stud.hs-esslingen.de/pub/Mirrors/ftp.apache.org/dist/tomee/tomee-7.1.0/apache-tomee-7.1.0-plume.zip -o $JZ_CACHE/$dist_zip
    fi

    if [ -d ${dist_zip%.zip} ]; then
        log_err "A folder ${dist_zip%.zip} already exists. Maybe delete it and try again."
        exit 1
    fi
    log_info "Extracting $dist_zip to this directory ..."
    unzip $JZ_CACHE/$dist_zip > /dev/null

    if [[ "${JZ_CUSTOM_RC}" == "" ]]; then
        export JZ_CUSTOM_RC=$(pwd)/.jeeez
    fi

    echo "export CATALINA_HOME=$(pwd)/${dist_zip%.zip}" >> $JZ_CUSTOM_RC
    log_success "Done."
    log_success "You can start TomEE with full Java EE 7 profile by running 'cd ${dist_zip%.zip}/bin; ./catalina.sh run'."
    # TODO: Support for Development Builds/Java EE 8
}

plugin_main_cmd "$@"