#!/usr/bin/env bash
set -eo pipefail; [[ $JZ_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"

#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

plugin_main_cmd() {

    if [ ! -f $JZ_CACHE/${JZ_TOMEE_DISTRIBUTION} ]; then
        log_info "Downloading $JZ_TOMEE_DISTRIBUTION to $JZ_CACHE ..."
        curl ${JZ_TOMEE_DOWNLOAD_URL}/${JZ_TOMEE_DISTRIBUTION} -o $JZ_CACHE/${JZ_TOMEE_DISTRIBUTION}
    fi

    local distribution=${JZ_TOMEE_DISTRIBUTION%.zip}

    if [ -d ${distribution} ]; then
        log_err "A folder ${distribution} already exists. Maybe delete it and try again."
        exit 1
    fi
    log_info "Extracting $JZ_TOMEE_DISTRIBUTION to this directory ..."
    unzip $JZ_CACHE/$JZ_TOMEE_DISTRIBUTION > /dev/null

    if [[ "${JZ_CUSTOM_RC}" == "" ]]; then
        export JZ_CUSTOM_RC=$(pwd)/.jeeez
    fi

    echo "export CATALINA_HOME=$(pwd)/${JZ_TOMEE_DISTRIBUTION%.zip}" >> $JZ_CUSTOM_RC
    log_success "Done."
    log_success "You can start TomEE with full Java EE 7 profile by running 'cd ${JZ_TOMEE_DISTRIBUTION%.zip}/bin; ./catalina.sh run'."
    # TODO: Support for Development Builds/Java EE 8
}

plugin_main_cmd "$@"