#!/usr/bin/env bash
set -o pipefail
set -o errexit

case "$1" in
  help)
    help_content_func () {
      cat<<help_content
    tomee:install; Download and extract TomEE in the current directory
help_content
    }
    help_content_func
    ;;
  *)
    exit 1
    ;;

esac


