sudo: required

language: java

services:
  - docker

before_install:
  - true

script:
  - cd tests; ./test_runner -s /bin/bash

after_error:
  - false

after_failure:
  - false

after_success:
  - true