= JEEEZ

image::https://api.travis-ci.org/38leinaD/jeeez.svg[]


JEEEZ (short: jz) is a command-line scaffolding tool that gets you started on developing a Java EE application in seconds.
It's just a set of Bash-scripts; so it should be running on most flavors of Linux, Unix, MacOSX and for Windows under Cygwin or MSYS.
Assuming you have Docker installed, you will even get your application deployed in seconds.

The tool is simple and optionated to serve my needs in demos and trainings.
It was originally created due to the non-existing scaffolding/archetype-mechanism in Gradle.

As I am using Gradle mainly, the tools is tested more thoroghly with Gradle. But Maven templates and support should still work fairly good.

== Installation

=== Automatic

----
curl https://raw.githubusercontent.com/38leinaD/jeeez/master/installer -sSf | sh
----

=== Manually from Git

----
$ git clone https://github.com/38leinaD/jeeez.git
$ echo "alias jz='$(pwd)/jeeez/jz'" >> ~/.bashrc
----

== Usage

Run the tool without any argument to get some help on the usage.

The main feature/command is `project:create`

----
$ jz project:create
Usage: jz project:create [groupid.]artifactid [OPTIONS]

Create a Java EE project from a template

Options:
    --jee-version=7|8 (default: 7)
    --template=ear|st|war (default: war)
    --st (creates a system-test project; same as --template=st)
    --build=gradle|maven (default: gradle)

Example:
$ jz project:create jz.myapp
    This will use some defaults (*) and create a project that...
    - is Java EE 7-compliant (*),
    - packages as a WAR archive (*),
    - has group-id "jz",
    - has artifact-id "myapp",
    - and builds with Gradle (*)
----

Now, lets scaffold, build and deploy a Java EE app.

=== Gradle

----
$ jz project:create de.dplatz.myapp
[INFO] Succesfully created a project with artifact-id 'myapp' and group-id 'de.dplatz' from template 'war'.
[INFO] ------------------------------------------------------------------------
[INFO] Build & run it with 'cd myapp; ./run_docker.sh'.
[INFO] Open http://localhost/myapp/resources/health when the sever is started.
[INFO] ------------------------------------------------------------------------
----

=== Maven

----
$ jz project:create de.dplatz.myapp --build=maven
----

=== System Tests

Have a check in the folder `test` for the test-scripts of this tool.
They provide good examples of what you can achive with just a few keystrokes.

E.g. you can also generate a system-tests project in addition to the main project.

----
$ jz project:create de.dplatz.myapp --st         
[INFO] Found parent-project @ myapp
[INFO] Succesfully created system-test project with artifact-id 'myapp-st' and group-id 'de.dplatz' from template 'st'.
[INFO] ------------------------------------------------------------------------
[INFO] Run them with 'cd myapp-st; ./gradlew systemTestInDockerEnv'.
[INFO] This project only works in conjunction with the project named 'myapp' located parallel to this project.
[INFO] Make sure to run  the build on it at least once to generate the artifact to deploy.
[INFO] ------------------------------------------------------------------------
$ cd myapp-st; ./gradlew systemTestInDockerEnv
----

System-tests are run against a docker-compose-based environment. See the myapp-st project for docker-compose.yml files for various application-servers.
The default being used in the docker-compose.yml is Wildfly. But to e.g. test against Websphere Liberty, just run:

----
$ cd myapp-st; ./gradlew systemTestInDockerEnv -PcomposeFile=docker-compose.wlp.yml
----

Docker compose files are provided for the following application-servers:

* Wildfly 13
* TomEE 7
* Websphere Liberty 18
* Websphere Traditional 9

=== EARs

TODO

=== Supported Application Servers

The following combinations of application-server and specifications are supported/tested.

|===
|                           | Java EE 7     | Java EE 8   | Microprofile 1.3 
| Wildfly 13                | x             | ?           |     
| TomEE 7                   | x             |             |       
| Websphere Liberty 18      | x             |             | ?   
| Websphere Traditional 9   | x             |             |   
|===

x = Supported/tested

? = Should work but not tested currently

== Todos

[] Support for Java EE 8 (`--jee-version` flag is not implemted yet)
[] Support for Payara/Glassfish
[] Support for MicroProfile