#!/usr/bin/env bash
set -o pipefail
set -o errexit

case "$1" in
  help)
    help_content_func () {
      cat<<help_content
    payara:install; Download and extract Payara in the current directory
help_content
    }
    help_content_func
    ;;
  *)
    exit 1
    ;;

esac


