#!/usr/bin/env bash
set -eo pipefail; [[ $JZ_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"

#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

plugin_main_cmd() {

    dist_zip="wildfly-14.0.0.Final.zip"

    if [ ! -f $JZ_CACHE/${dist_zip} ]; then
        log_info "Downloading ${dist_zip} to $JZ_CACHE ..."
        curl http://download.jboss.org/wildfly/14.0.0.Final/wildfly-14.0.0.Final.zip -o $JZ_CACHE/${dist_zip}
    fi

    if [ -d ${dist_zip} ]; then
        log_err "A folder ${dist_zip} already exists. Maybe delete it and try again."
        exit 1
    fi
    log_info "Extracting ${dist_zip} to this directory ..."
    unzip $JZ_CACHE/${dist_zip} > /dev/null

    if [[ "${JZ_CUSTOM_RC}" == "" ]]; then
        export JZ_CUSTOM_RC=$(pwd)/.jeeez
    fi

    folder_name=${dist_zip%.zip}

    echo "export JBOSS_HOME=$(pwd)/$folder_name" >> $JZ_CUSTOM_RC
    log_success "Done."
    log_success "You can start Wildfly by running 'cd $folder_name/bin; ./standalone.sh -c standalone-full.xml'."
    # TODO: create a run_wildfly.sh in project
}

plugin_main_cmd "$@"