#!/usr/bin/env bash
set -eo pipefail; [[ $JZ_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"

#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

plugin_main_cmd() {

    if [ ! -f $JZ_CACHE/wildfly-13.0.0.Final.zip ]; then
        log_info "Downloading wildfly-13.0.0.Final.zip to $JZ_CACHE ..."
        curl http://download.jboss.org/wildfly/13.0.0.Final/wildfly-13.0.0.Final.zip -o $JZ_CACHE/wildfly-13.0.0.Final.zip
    fi

    if [ -d wildfly-13.0.0.Final ]; then
        log_err "A folder wildfly-13.0.0.Final already exists. Maybe delete it and try again."
        exit 1
    fi
    log_info "Extracting wildfly-13.0.0.Final.zip to this directory ..."
    unzip $JZ_CACHE/wildfly-13.0.0.Final.zip > /dev/null

    if [[ "${JZ_CUSTOM_RC}" == "" ]]; then
        export JZ_CUSTOM_RC=$(pwd)/.jeeez
    fi

    echo "export JBOSS_HOME=$(pwd)/wildfly-13.0.0.Final" >> $JZ_CUSTOM_RC
    log_success "Done."
    log_success "You can start Wildfly with full Java EE 7 profile by running 'cd wildfly-13.0.0.Final/bin; ./standalone.sh -c standalone-full.xml'."
    log_success "You can start Wildfly with full Java EE 8 profile by running 'cd wildfly-13.0.0.Final/bin; ./standalone.sh -c standalone-ee8.xml'."
    # TODO: create a run_wildfly.sh in project
}

plugin_main_cmd "$@"