#!/usr/bin/env bash
set -eo pipefail; [[ $JZ_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"

#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

plugin_main_cmd() {

    dist_zip="wildfly-14.0.0.Final.zip"

    if [ ! -f $JZ_CACHE/${JZ_WILDFLY_DISTRIBUTION} ]; then
        log_info "Downloading ${JZ_WILDFLY_DISTRIBUTION} to $JZ_CACHE ..."
        curl ${JZ_WILDFLY_DOWNLOAD_URL}/${JZ_WILDFLY_DISTRIBUTION} -o $JZ_CACHE/${JZ_WILDFLY_DISTRIBUTION}
    fi

    if [ -d ${JZ_WILDFLY_DISTRIBUTION} ]; then
        log_err "A folder ${JZ_WILDFLY_DISTRIBUTION} already exists. Maybe delete it and try again."
        exit 1
    fi
    log_info "Extracting ${JZ_WILDFLY_DISTRIBUTION} to this directory ..."
    unzip $JZ_CACHE/${JZ_WILDFLY_DISTRIBUTION} > /dev/null

    if [[ "${JZ_CUSTOM_RC}" == "" ]]; then
        export JZ_CUSTOM_RC=$(pwd)/.jeeez
    fi

    folder_name=${JZ_WILDFLY_DISTRIBUTION%.zip}

    echo "export JBOSS_HOME=$(pwd)/$folder_name" >> $JZ_CUSTOM_RC
    log_success "Done."
    log_success "You can start Wildfly by running 'cd $folder_name/bin; ./standalone.sh -c standalone-full.xml'."
    # TODO: create a run_wildfly.sh in project
}

plugin_main_cmd "$@"