#!/usr/bin/env bash
set -eo pipefail; [[ $JZ_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"
source "$PLUGIN_PATH/database/functions"

#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

usage() {
    echo "Usage: jz wildfly:jdbc postgresql|oracle"
    echo ""
    echo "???"
}

plugin_main_cmd() {

    if [ "$1" == "" ]; then
        usage
        exit 1
    fi

    database_type=$1
    shift

    download_jdbc_driver $database_type

    jdbc_driver_path=$(get_jdbc_driver_path $database_type)
    jdbc_driver_file=$(basename $jdbc_driver_path)

    if [ -f bin/standalone.sh ]; then
        export JBOSS_HOME=$(pwd)
    fi

    if ! [[ -v JBOSS_HOME ]]; then
        log_err "Environment variable JBOSS_HOME is not set."
        exit 1
    fi
    (
        cd $JBOSS_HOME

        SERVER_CONFIG="standalone-full.xml"
        log_info "Configuring $database_type JDBC Driver in ${SERVER_CONFIG}."
        echo "SERVER_CONFIG=$SERVER_CONFIG" > /var/tmp/env.properties
        echo "JDBC_DRIVER_PATH=${jdbc_driver_path}" >> /var/tmp/env.properties
        ./bin/jboss-cli.sh --file=$PLUGIN_PATH/wildfly/cli-scripts/jdbc-${database_type}.cli --properties=/var/tmp/env.properties
        log_success "Done. Check '$JBOSS_HOME/standalone/configuration/$SERVER_CONFIG' for details."

        SERVER_CONFIG="standalone-ee8.xml"
        log_info "Configuring $database_type JDBC Driver in ${SERVER_CONFIG}."
        echo "SERVER_CONFIG=$SERVER_CONFIG" > /var/tmp/env.properties
        echo "JDBC_DRIVER_PATH=${jdbc_driver_path}" >> /var/tmp/env.properties
        ./bin/jboss-cli.sh --file=$PLUGIN_PATH/wildfly/cli-scripts/jdbc-${database_type}.cli --properties=/var/tmp/env.properties
        log_success "Done. Check '$JBOSS_HOME/standalone/configuration/$SERVER_CONFIG' for details."
    )
    rm -f /var/tmp/env.properties
    
}

plugin_main_cmd "$@"