#!/usr/bin/env bash
set -eo pipefail; [[ $JZ_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"

write_metadata_file() {
    echo "jz_pj_build=$_build" > .jeeezmeta
    echo "jz_pj_template=$_template" >> .jeeezmeta
}

source_metadata_file() {
    source .jeeezmeta
}

to_project_coordinates() {
    if [[ $(expr index "$project_name" .) != "0" ]] ; then
        # project-name contains dot and thus a group-id
        jz_pj_groupid=$(echo "$project_name" | rev | cut -d"." -f2-  | rev)
        jz_pj_artifactid=$(echo "$project_name" | rev | cut -d"." -f1  | rev)
    else
        jz_pj_groupid="jz"
        jz_pj_artifactid="$project_name"
    fi
    jz_pj_folder_name=$jz_pj_artifactid
    jz_pj_folder_path=$(pwd)/$jz_pj_folder_name
}

infer_project_details() {
    local project_folder=$1

    if [ -f build.gradle ]; then
        jz_project_build="gradle"
    else
        jz_project_build="maven"
    fi
}

apply_template() {
    local template_name=$1
    local work_folder_name=$2

    cp -r $PLUGIN_PATH/project/templates/$template_name $work_folder_name

    find $work_folder_name -type d -name "packagename" | while read dir; do
        # Derive packagenames from groupid/artifactid
        local parent=$(dirname $dir)
        local artifact_dir="${jz_pj_artifactid//-/}"
        local package_dirs="${jz_pj_groupid//.//}/${artifact_dir}"
        local package_path="$parent/$package_dirs"
        mkdir -p "$package_path"
        mv $dir/* $package_path/ || true
        rm -rf $dir
    done

    # Fix packagenames in Java-code
    local java_package_name="${jz_pj_groupid}.${jz_pj_artifactid//-/}"
    find $work_folder_name -type f \( -name "*.java" -o -name "build.gradle" \) -exec sed -i "s/packagename/${java_package_name}/g" {} \;

    # Fix subproject folder-names
    find $work_folder_name -type d -name "template-artifactid-*" | while read file; do \
        #dir=$(dirname $f)
        #file=$(basename $f)
        #rename "s/template-artifactid-(.*)\$/$jz_pj_artifactid-\$1/" $f
        newfile=${file/template-artifactid/$jz_pj_artifactid}
        mv $file $newfile
    done;

    # Set groupid/artifactid in pom.xml/build.gradle
    find $work_folder_name -type f -exec sed -i "s/template-artifactid/${jz_pj_artifactid}/g" {} \;
    find $work_folder_name -type f -exec sed -i "s/template-groupid/${jz_pj_groupid}/g" {} \;
}