#!/usr/bin/env bash
set -eo pipefail; [[ $JZ_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"

#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

plugin_main_cmd() {

    if [ ! -f $JZ_CACHE/${JZ_LIBERTY_DISTRIBUTION} ]; then
        log_info "Downloading ${JZ_LIBERTY_DISTRIBUTION} to $JZ_CACHE ..."
        curl ${JZ_LIBERTY_DOWNLOAD_URL}/${JZ_LIBERTY_DISTRIBUTION} -o $JZ_CACHE/${JZ_LIBERTY_DISTRIBUTION}
    fi

    local distribution=${JZ_LIBERTY_DISTRIBUTION%.zip}

    if [ -d ${distribution} ]; then
        log_err "A folder ${distribution} already exists. Maybe delete it and try again."
        exit 1
    fi
    log_info "Extracting ${JZ_LIBERTY_DISTRIBUTION} to this directory ..."
    unzip $JZ_CACHE/${JZ_LIBERTY_DISTRIBUTION} > /dev/null
    mv wlp ${distribution}

    if [[ "${JZ_CUSTOM_RC}" == "" ]]; then
        export JZ_CUSTOM_RC=$(pwd)/.jeeez
    fi

    echo "export WLP_HOME=$(pwd)/${distribution}" >> $JZ_CUSTOM_RC
    log_success "Done."
    log_hr
    log_info "You can start Liberty with full Java EE 7 profile by running 'cd ${distribution}/bin; ./server create --template=javaee7; ./server run'."
    log_info "For Java EE 8, get the latest 'Development build' from https://openliberty.io/downloads/. Extract it and run './server create --template=javaee8'; ./server run'."
    # TODO: Support for Development Builds/Java EE 8
}

plugin_main_cmd "$@"