#!/usr/bin/env bash
set -eo pipefail; [[ $JZ_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"

#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

plugin_main_cmd() {

    if [ ! -f $JZ_CACHE/$JZ_PAYARA_DISTRIBUTION ]; then
        log_info "Downloading payara-5.181.zip to $JZ_CACHE ..."
        curl $JZ_PAYARA_DOWNLOAD_URL/$JZ_PAYARA_DISTRIBUTION -o $JZ_CACHE/$JZ_PAYARA_DISTRIBUTION
    fi

    if [ -d payara5 ]; then
        log_err "A folder payara5 already exists. Maybe delete it and try again."
        exit 1
    fi
    log_info "Extracting $JZ_PAYARA_DISTRIBUTION to this directory ..."
    unzip $JZ_CACHE/payara-5.181.zip > /dev/null

    if [[ "${JZ_CUSTOM_RC}" == "" ]]; then
        export JZ_CUSTOM_RC=$(pwd)/.jeeez
    fi

    echo "export PAYARA_HOME=$(pwd)/payara5" >> $JZ_CUSTOM_RC
    echo "export DEPLOY_TO=$(pwd)/payara5/glassfish/domains/domain1/autodeploy" >> $JZ_CUSTOM_RC
    log_success "Done."
    log_success "You can start Payara with full Java EE 8 profile by running 'cd payara5/bin; ./asadmin start-domain --verbose'."
}

plugin_main_cmd "$@"