#!/usr/bin/env bash
set -eo pipefail; [[ $JZ_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"

#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

list_templates() {
    # TODO: Print nice description for templates
    find $PLUGIN_PATH/project/templates -maxdepth 1 -type d -print | tail -n +2 | rev | cut -d'/' -f 1 | rev
}

_build="gradle"
_template="war"
_jee_version="7"


usage() {
    templates=$(list_templates | paste -sd "|" -)
    echo "Usage: jz project:create [groupid.]artifactid [OPTIONS]"
    echo ""
    echo "Create a Java EE project from a template"
    echo ""
    echo "Options:"
    echo "    --jee-version=7|8 (default: 7)"
    echo "    --template=$templates (default: war)"
    echo "    --st (creates a system-test project; same as --template=st)"
    echo "    --build=gradle|maven (default: gradle)"
    echo ""
    echo "Example:"
    echo "$ jz project:create jz.myapp"
    echo "    This will use some defaults (*) and create a project that..."
    echo "    - is Java EE 7-compliant (*),"
    echo "    - packages as a WAR archive (*),"
    echo "    - has group-id \"jz\","
    echo "    - has artifact-id \"myapp\","
    echo "    - and builds with Gradle and Maven. (*)"
}

scaffold() {
    local groupid=$1
    local artifactid=$2
    
    cp -r $PLUGIN_PATH/project/templates/$_template $artifactid

    find $artifactid -type d -name "packagename" | while read dir; do
        # Derive packagenames from groupid/artifactid
        local parent=$(dirname $dir)
        local artifact_dir="${artifactid//-/}"
        local package_dirs="${groupid//.//}/${artifact_dir}"
        local package_path="$parent/$package_dirs"
        mkdir -p "$package_path"
        mv $dir/* $package_path/ || true
        rm -rf $dir
    done

    # Fix packagenames in Java-code
    local java_package_name="${groupid}.${artifactid//-/}"
    find $artifactid -type f \( -name "*.java" -o -name "build.gradle" \) -exec sed -i "s/packagename/${java_package_name}/g" {} \;

    # Fix subproject folder-names
    find $artifactid -type d -name "template-artifactid-*" -print0
    find $artifactid -type d -name "template-artifactid-*" | while read file; do \
        #dir=$(dirname $f)
        #file=$(basename $f)
        #rename "s/template-artifactid-(.*)\$/$artifactid-\$1/" $f
        newfile=${file/template-artifactid/$artifactid}
        mv $file $newfile
    done;

    # Set groupid/artifactid in pom.xml/build.gradle
    find $artifactid -type f -exec sed -i "s/template-artifactid/${artifactid}/g" {} \;
    find $artifactid -type f -exec sed -i "s/template-groupid/${groupid}/g" {} \;

    if ! [[ -v JZ_CUSTOM_ROOT ]]; then
        touch .jeeez
    fi

    if [[ "$_build" == "maven" ]]; then
        rm -rf $artifactid/gradle
        rm -f $artifactid/gradlew*
        rm -f $artifactid/settings.gradle
        find $artifactid -type f -exec sed -i "s/template-artifactid/${artifactid}/g" {} \;
        find $artifactid -type f -name "build.gradle" -exec rm -f {} \;
    elif [[ "$_build" == "gradle" ]]; then
        rm -rf $artifactid/.mvn
        rm -f $artifactid/mvnw*
        find $artifactid -type f -name "pom.xml" -exec rm -f {} \;
    fi

    if [[ "$artifactid" == *-st ]]; then
        # This is a system-test project
        # Find the main project this belongs to
        parent_artifactid=${artifactid%-st}
        if [ -d "$parent_artifactid" ]; then
            log_info "Found parent-project @ $parent_artifactid"
            echo "COMPOSE_PROJECT_NAME=$parent_artifactid" >> $artifactid/.env
            find $artifactid -type f -exec sed -i "s/template-parent-artifactid/${parent_artifactid}/g" {} \;
            
            if [[ "$_build" == "maven" ]]; then
                find $artifactid -type f -exec sed -i "s/build\/libs/target/g" {} \;
            fi
            (
                APPNAME=$parent_artifactid
                for composeFile in $artifactid/docker-compose*.yml; do
                    create_file_from_template $composeFile $composeFile
                done
            )
        else
            log_err "Expected a main-project named '$parent_artifactid' but unable to find."
            exit 1
        fi

        log_success "Succesfully created system-test project with artifact-id '$artifactid' and group-id '$groupid' from template '$_template'."
        log_info $HR
        if [[ "$_build" == "maven" ]]; then
            log_info "Run them with 'cd $artifactid; ./mvnw verify'."
        else
            log_info "Run them with 'cd $artifactid; ./gradlew systemTestInDockerEnv'."
        fi
        log_info "This project only works in conjunction with the project named '$parent_artifactid' located parallel to this project."
        log_info "Make sure to run  the build on it at least once to generate the artifact to deploy."
        log_info $HR
    else
        log_success "Succesfully created a project with artifact-id '$artifactid' and group-id '$groupid' from template '$_template'."
        log_info $HR
        log_info "Build & run it with 'cd $artifactid; ./run_docker.sh'."
        log_info "Open http://localhost/$artifactid/resources/health when the sever is started."
        log_info $HR
    fi
    #tree -C $artifactid/
}

plugin_main_cmd() {

    case $1 in
        -h|--help)
        usage
        exit 0
        ;;
    esac

    if [ "$1" == "" ]; then
        usage
        exit 1
    fi

    local project_name=$1
    shift

    while [ $# -gt 0 ]; do
    case "$1" in
        --jee-version=*)
        _jee_version="${1#*=}"
        ;;
        --template=*)
        _template="${1#*=}"
        ;;
        --st)
        # If we are generating a system-test project, append "-st" to project-name
        project_name="${project_name}-st"
        _template="st"
        ;;
        --build=*)
        _build="${1#*=}"
        ;;
        *)
        log_err "Invalid argument"
        exit 1
    esac
    shift
    done

    if [[ $(expr index "$project_name" .) != "0" ]] ; then
        # project-name contains dot and thus a group-id
        groupid=$(echo "$project_name" | rev | cut -d"." -f2-  | rev)
        artifactid=$(echo "$project_name" | rev | cut -d"." -f1  | rev)
    else
        groupid="jz"
        artifactid="$project_name"
    fi

    if ! [ -d $PLUGIN_PATH/project/templates/$_template ]; then
        log_err "No template with name '$_template'"
        exit 1
    fi

    scaffold $groupid $artifactid
}

plugin_main_cmd "$@"