#!/usr/bin/env bash
set -eo pipefail; [[ $JZ_TRACE ]] && set -x
source "$PLUGIN_PATH/common/functions"
source "$PLUGIN_PATH/project/functions"

#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

list_templates() {
    # TODO: Print nice description for templates
    find $PLUGIN_PATH/project/templates -maxdepth 1 -type d -print | tail -n +2 | rev | cut -d'/' -f 1 | rev
}

_build="gradle"
_template="war"
_jee_version="7"


usage() {
    templates=$(list_templates | paste -sd "|" -)
    echo "Usage: jz project:create [groupid.]artifactid [OPTIONS]"
    echo ""
    echo "Creates a Java EE project from a template"
    echo ""
    echo "Options:"
    echo "    --jee-version=7|8 (default: 7)"
    echo "    --template=$templates (default: war)"
    echo "    --st (creates a system-test project; same as --template=st)"
    echo "    --ear (creates an EAR project; same as --template=ear)"
    echo "    --build=gradle|maven (default: gradle)"
    echo "    --maven (creates an Maven project; same as --build=maven)"
    echo ""
    echo "Example:"
    echo "$ jz project:create jz.myapp"
    echo "    This will use some defaults (*) and create a project that..."
    echo "    - is Java EE 7-compliant (*),"
    echo "    - packages as a WAR archive (*),"
    echo "    - has group-id \"jz\","
    echo "    - has artifact-id \"myapp\","
    echo "    - and builds with Gradle (*)"
}

scaffold() {   
    if [[ "$jz_pj_folder_name" == *-st && ! -d $jz_pj_artifactid ]]; then
        log_err "Main project '$jz_pj_artifactid' not found."
        log_err "The system-test project requires a main project with name '$jz_pj_artifactid'."
        log_err "Maybe run 'jz project:create $jz_pj_groupid.$jz_pj_artifactid' to create it?"
        exit 1
    fi

    apply_template $_template $jz_pj_folder_name

    if ! [[ -v JZ_CUSTOM_ROOT ]]; then
        touch .jeeez
    fi
    
    if [ -f $jz_pj_folder_name/.gitignore ]; then
        # Ignore .vscode-folder
        echo ".vscode" >> $jz_pj_folder_name/.gitignore
    fi

    log_info $HR
    if [[ "$jz_pj_folder_name" == *-st ]]; then
        log_success "Succesfully created system-test project with artifact-id '$jz_pj_artifactid' and group-id '$jz_pj_groupid' from template '$_template'."
        log_info $HR
        if [[ "$_build" == "maven" ]]; then
            log_info "Run them with '${BOLD}./mvnw verify${RESTORE}'."
        else
            log_info "Run them with '${BOLD}./gradlew systemTest${RESTORE}'."
        fi
        log_info "This project only works in conjunction with the project named '$parent_artifactid' located parallel to this project."
        log_info "Make sure to run  the build on it at least once to generate the artifact to deploy."
        log_info $HR
    else
        log_success "Succesfully created a project with artifact-id '$jz_pj_artifactid' and group-id '$jz_pj_groupid' from template '$_template'."
        log_info $HR
        log_info "Build & run it with '${BOLD}./run_docker.sh${RESTORE}'."
        log_info "Open http://localhost/$jz_pj_artifactid/resources/health when the server is started."

        if [[ "$_build" == "gradle" ]]; then
            log_info $HR
            log_info "Build, run & system-test it with '${BOLD}./gradlew systemTest${RESTORE}'."
        fi
        log_info $HR
    fi
    #tree -C $jz_pj_artifactid/
}

plugin_main_cmd() {

    case $1 in
        -h|--help)
        usage
        exit 0
        ;;
    esac

    if [ "$1" == "" ]; then
        usage
        exit 1
    fi

    local project_name=$1
    shift

    while [ $# -gt 0 ]; do
    case "$1" in
        --jee-version=*)
        _jee_version="${1#*=}"
        ;;
        --template=*)
        _template="${1#*=}"
        ;;
        --st)
        _template="st"
        ;;
        --ear)
        _template="ear"
        ;;
        --build=*)
        _build="${1#*=}"
        ;;
        --maven)
        _build="maven"
        ;;
        *)
        log_err "Invalid argument"
        exit 1
    esac
    shift
    done

    to_project_coordinates $project_name

    if [[ $_template == "st" ]]; then
        # If we are generating a system-test project, append "-st" to project-name
        jz_pj_folder_name="${jz_pj_artifactid}-st"
    else
        jz_pj_folder_name="${jz_pj_artifactid}"
    fi
    jz_pj_folder_path=$(pwd)/$jz_pj_folder_name

    if ! [ -d $PLUGIN_PATH/project/templates/$_template ]; then
        log_err "No template with name '$_template'"
        exit 1
    fi

    scaffold
}

plugin_main_cmd "$@"