#!/usr/bin/env bash
set -o pipefail
set -o errexit

case "$1" in
  help)
    help_content_func () {
      cat<<help_content
    database:use; Generate scripts to start a database as docker container
help_content
    }
    help_content_func
    ;;
  *)
    exit 1
    ;;

esac


