#!/usr/bin/env bash
set -o pipefail
set -o errexit

case "$1" in
  help)
    help_content_func () {
      cat<<help_content
    wildfly:install; Download and extract Wildfly in the current directory
    wildfly:jdbc; Configure JDBC driver in Wildfly
help_content
    }
    help_content_func
    ;;
  *)
    exit 1
    ;;

esac


