#!/usr/bin/env bash
set -eo pipefail; [[ $JZ_TRACE ]] && set -x

RESTORE='\e[0m'
RED='\e[00;91m'
WHITE='\e[1;37m'
GREEN='\e[00;92m'
YELLOW='\e[93m'
BLUE='\e[94m'
CYAN='\e[1;36m'
HR='------------------------------------------------------------------------'

has_tty() {
  if [[ "$(/usr/bin/tty || true)" == "not a tty" ]]; then
    return 1
  else
    return 0
  fi
}

create_file_from_template() {
    eval "cat <<EOF
$(<$2)
EOF" > $1
}

ask_yes_no() {
    while true; do
        read -p "$1 [(y)es,(n)o] " yn
        case $yn in
            [Yy]* ) return 0; break;;
            [Nn]* ) return 1; break;;
            * ) echo "Please answer yes or no.";;
        esac
    done    
}

parse_args() {
  local next_index=1; local skip=false; local args=("$@")
  for arg in "$@"; do
    $skip && skip=false && continue
    case "$arg" in
      --trace)
        export JZ_TRACE=1
        ;;
      --debug)
        export JZ_DEBUG=1
        ;;
    esac
    local next_index=$(( next_index + 1 ))
  done
  return 0
}

log_hr() {
    log_info $HR
}

log_info() {
    echo -en "[${BLUE}INFO${RESTORE}] $*\n" >&2
}

log_success() {
    log_info "${GREEN}$*${RESTORE}"
}

log_warn() {
    echo -en "[${YELLOW}WARN${RESTORE}] $*\n" >&2
}

log_err() {
    echo -en "[${RED}ERROR${RESTORE}] $*\n" >&2
    #if [ -x "$(command -v notify-send)" ]; then
    #    notify-send -u critical "$*"
    #fi
}

log_debug() {
    [[ $JZ_DEBUG == 1 ]] && echo -en "${CYAN}[DEBUG]${RESTORE} $*\n" || true
}

root_walk() {
    f=$1
    path_node=$(pwd)
    while true; do
        if [[ $path_node == / ]]; then
            # nothing found
            break
        elif [ -f "${path_node}/$f" ]; then
            # found
            echo "$path_node/$f"
            break
        else
            # go up
            path_node="$(dirname "$path_node")"
        fi
    done
}